{
    'name': 'Maintenance Modification',
    'version': '16.0.1.0.2',
    'author': 'Uzair Ahmed | Odolution',
    'license': 'OPL-1',
    'description':"""
      
        """,
    'depends': ['base','maintenance','account_asset','hr','account', 'web','stock'],
    "data": [
        "security/ir.model.access.csv",
        "views/view_discipline.xml",
        "views/fault_category.xml",
        "views/maintenance_equipment_cat.xml",
        "views/maintenance_request.xml",
        "views/functional_location.xml",
        "views/maintenance_menuitem.xml",
        "views/maintenance_team_views.xml",
        "views/stock_picking.xml",
        "views/sequence_wr_no.xml",
        "reports/report_maintenance_request_form.xml",
        "reports/report_machine_history_sheet.xml",
        "reports/report_machine_history_sheet_all.xml",
        "reports/report_preventive_maintenance_plan.xml",
        "reports/report_preventive_maintenance_report.xml",
        "wizard/machine_history_sheet_wizard_view.xml",
        "wizard/machine_history_sheet_all_wizard.xml",
        "wizard/preventive_maintenance_plan_wizard.xml",
        "wizard/preventive_maintenance_report_wizard.xml",
    ],
    # 'images': ['static/description/banner.png'],
    'application': True,
    'installable': True,
    'auto_install': False,
}
