{
    'name': 'Quality Control',
    'version': '16.0.1',
    'summary': 'Quality Control',
    'sequence': -100,
    'author': 'Okasha Bin Ghaffar',
    'license': 'OPL-1',
    'website': '',
    'description':"""
      
        """,
    'depends': ['prodo_x_biafo_ext','quality_control','gate_module','account_asset', 'account'],
    'data':[
        'views/groups.xml',
        'views/qir_view.xml',
        'views/rqi_tree_view.xml',
        'views/mrp_production_form.xml',
        'views/stock_picking_form.xml',
        'views/view_pdo_form.xml',
        'views/sale_order_view.xml',
         'views/purchase_order.xml',
         'views/asset_view.xml',
        # 'views/purchase_request.xml',
        'views/res_partner.xml',
        'views/approval_request.xml',
        'views/quality_inspection_report_wizard.xml',
        'security/ir.model.access.csv',
        # 'views/quality_check_view.xml',
    ],
    'assets': {},
    'application': True,
    'installable': True,
    'auto_install': False,
}
